#
# 节点启动配置
#

# 数据目录
#datadir: ~/.hacash
datadir: /media/yangjie/500GB/Hacash/src/github.com/hacash/blockmint/database_debug

loglevel: "Debug"

# 矿工配置
miner:
#  forcestart: true
#  backtoheight: 800 # 区块状态退回到指定高度
  stepsleepnano: 5000KK
  minfeeratio: 100Y
  rewards:
  - 127717zvZWFjEghjEpyyRSnitEEbnMuuLn
  - 1799951NwpyxekkraYtAbYVuydDfGsMiQ
  - 126517vPvexxaivGSUGewzrsxREUTnhKcR



## ------------------------------------------------------- ##



# p2p 配置
p2p:
  port: { node: 3337, rpc: 3338 }
  myname: hacash_debug # 本节点名称
  bootnodes: # 初始节点
  - enode://f62b3ae0b549ab18a48189778948403fec3f2ebcd6b855ded0ddfb7d1c68c3ac7f15143c3ba5b60114065c5d370eb60402fccac1bc252dd0c9e205f87345a4f1@127.0.0.1:33371






